apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders:
      - name: cookiex-extauth
        envoyExtAuthzHttp:
          #service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          #service: cookie-x-app.svc.cluster.local
          #service: cookie-x-app
          service: cookie-x-app.default.svc.cluster.local
          port: 8081
          timeout: 1s
          includeRequestHeadersInCheck:
            - Cookie
          headersToUpstreamOnAllow:
            - authorization
            - hello
          #headersToDownstreamOnDeny:
          #  - set-cookie
